#!/usr/bin/env bash
# This file is responsible for downloading all dependencies necessary to run my set-up of Bash and Neovim in Ubuntu.

# Both apt-get and snap require root privledges
check_su() {
    if [[ $(id -u) != "0" ]]; then
        printf "%s\n\n" "You must be the superuser to run this script (try 'sudo -s')"
        exit -1
    fi
}

install_git() {
    if ! [[ -x "$(command -v git)" ]]; then
        return
    fi
        apt-get install git 
}

install_curl() {
    if ! [[ -x "$(command -v curl)" ]]; then
        return
    fi
        apt-get install curl 
}

install_node() {
    if ! [[ -x "$(command -v node)" ]]; then
        return
    fi
        snap install node --classic --channel=edge # Installs both node and npm
}

install_rg() {
    if ! [[ -x "$(command -v rg)" ]]; then
        return
    fi
        curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
        dpkg -i ripgrep_12.1.1_amd64.deb
        rm ripgrep_12.1.1_amd64.deb # This method of installation leaves behind a .deb
}

install_bat() {
    if ! [[ -x "$(command -v batcat)" ]]; then
        return
    fi
        snap install batcat # Aliased to 'bat' in .bashrc
}

install_fd() {
    if ! [[ -x "$(command -v fdfind)" ]]; then
        return
    fi
        apt-get install fd-find # Aliased to 'fd' in .bashrc
}

install_fzf() {
    if ! [[ -x "$(command -v fzf)" ]]; then
        return
    fi
        apt-get install fzf
}

install_nvim() {
    if ! [[ -x "$(command -v nvim)" ]]; then
        return
    fi
        apt-get install neovim
}

install_vimplug() {
    sh -c "curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
}

install_dependencies() {
    apt-get update
    printf "%s\n\n" "Updated 'apt-get' to most recent version"

    printf "%s\n\n" "Downloading dependencies..."
    declare -a dependencies=(
        install_git
        install_curl
        install_node
        install_rg
        install_bat
        install_fd
        install_fzf
        install_nvim
        install_vimplug
    )

    failure=false
    for cmd in "${dependencies[@]}"; do
        $cmd
        if [[ $? -eq 0 ]]; then
            printf "%s\n\n" "Successfully ran '$cmd'"
        else
            printf "%s\n\n" "Failed to run '$cmd'"
            failure=true
        fi
    done

    if [[ $failure = true ]]; then
        printf "\n%s\n" "ERROR: One or more dependencies was not installed properly"
    else
        printf "\n%s\n" "SUCCESS: All dependencies were installed successfully"
    fi
}

main() {
    printf "%s\n" "dependencies - $(date)"
    printf "%s\n" "============================================================"
    check_su
    install_dependencies
    printf "%s\n" "============================================================"
}

main "$@" 2>&1 | tee -a log.txt # Logs both STDOUT and STDERR
